#Site config
username: ChanceYu
title: "Front End Math"
description: "使用 JavaScript、HTML、CSS，以及其它前端技术整理的一个与数学有关的代码片段集合与案例展示。"
keywords: front-end math ChanceYu 数学
url: /
feed: 
theme: jekyll-theme-cayman


# Build settings
gems:
  - jemoji